print("方案一:")
print("人羊狼菜 狼菜 人狼菜")
print("狼")
print("人羊狼")
print("羊 人羊 空")
print("方案二:")
print("人羊狼菜 狼菜 人狼菜")
print("狼")
print("人羊狼")
print("菜")
print("人羊菜")
print("羊 人羊 空")
print("方案三:")
print("人羊狼菜 狼菜 人狼菜")
print("菜")
print("人羊狼")
print("羊 人羊 空")
print("方案四:")
print("人羊狼菜 狼菜 人狼菜")
print("菜")
print("人羊菜")
print("羊 人羊 空")
